version: '3.8'

services:
  # MySQL 数据库
  db:
    image: mysql:8.0
    container_name: trip_planner_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-trip_planner}
      MYSQL_USER: ${MYSQL_USER:-trip_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-trip_password}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-password}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - trip_planner_network

  # 应用服务
  app:
    build: .
    container_name: trip_planner_app
    restart: always
    depends_on:
      - db
    environment:
      - FLASK_ENV=${FLASK_ENV:-production}
      - SECRET_KEY=${SECRET_KEY:-your-secret-key}
      - DATABASE_URL=mysql+pymysql://${MYSQL_USER:-trip_user}:${MYSQL_PASSWORD:-trip_password}@db/${MYSQL_DATABASE:-trip_planner}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-your-jwt-secret-key}
      - AMAP_KEY=${AMAP_KEY:-your-amap-key}
      - WECHAT_APP_ID=${WECHAT_APP_ID:-your-wechat-app-id}
      - WECHAT_APP_SECRET=${WECHAT_APP_SECRET:-your-wechat-app-secret}
    volumes:
      - ./app:/app/app
      - ./logs:/app/logs
    networks:
      - trip_planner_network

  # Nginx 服务
  nginx:
    image: nginx:1.21-alpine
    container_name: trip_planner_nginx
    restart: always
    depends_on:
      - app
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./static:/usr/share/nginx/html
      - nginx_logs:/var/log/nginx
    ports:
      - "${NGINX_PORT:-80}:80"
    networks:
      - trip_planner_network

  # 数据库初始化服务
  db_init:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trip_planner_db_init
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-trip_planner}
    command: python scripts/init_db.py
    volumes:
      - ./scripts:/app/scripts
      - ./docker/mysql/init:/app/docker/mysql/init
    networks:
      - trip_planner_network

networks:
  trip_planner_network:
    driver: bridge

volumes:
  mysql_data:
  nginx_logs:
